package net.webservicex;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T14:13:46.114+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.webservicex.net/", name = "OFACSDNHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface OFACSDNHttpGet {
}
