package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T14:13:46.204+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.webservicex.net/", name = "OFACSDNSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OFACSDNSoap {

    /**
     * This web services was created to aid banks in meeting the requirements of the US Treasury Department's Office of Foreign Asset Control (OFAC). OFAC restricts transactions with specific countries, organizations and individuals.
     */
    @RequestWrapper(localName = "IsSDNAndBlockedPersons", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.IsSDNAndBlockedPersons")
    @WebMethod(operationName = "IsSDNAndBlockedPersons", action = "http://www.webservicex.net/IsSDNAndBlockedPersons")
    @ResponseWrapper(localName = "IsSDNAndBlockedPersonsResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.IsSDNAndBlockedPersonsResponse")
    public void isSDNAndBlockedPersons(
        @WebParam(name = "Names", targetNamespace = "http://www.webservicex.net/")
        java.lang.String names,
        @WebParam(mode = WebParam.Mode.OUT, name = "IsSDNAndBlockedPersonsResult", targetNamespace = "http://www.webservicex.net/")
        javax.xml.ws.Holder<java.lang.Boolean> isSDNAndBlockedPersonsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "SDNLists", targetNamespace = "http://www.webservicex.net/")
        javax.xml.ws.Holder<SDNList> sdnLists
    );
}
